apiVersion: autoscaling.itsmekhoathekid.dev/v1alpha1
kind: RiverPredictiveHorizontalPodAutoscaler
metadata:
  name: house-price-api
  namespace: predictive-hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: house-price-api
  minReplicas: 1
  maxReplicas: 8
  syncPeriod: 10s
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  models:
    - type: RiverLinearRegression
      name: house-price-online
      perSyncPeriod: 1
      riverLinearRegression:
        lookAhead: 10s
        updateMode: datapoint
        batchSize: 1
        learningRate: 0.01
        warmupSamples: 6
        checkpointInterval: 1m
        mode: observe
  decisionType: maximum
